version: '3.9'
services:
  db:
    container_name: objedname_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_SQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_SQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d